### ISSUE TITLE
[BACKEND] Create '/api/ingredients/next' endpoint - 'GET' option.

### ISSUE THREAD

**Issue by MateuszWojtynski** [SoftwareEngineeringGroup3-3/recipe-app-backend#40]
Functionality:
`Returns list of next possible ingredients`

**Comment by Nomi** [comment]
Issue unclear. Specification doesn't contain a GET option for the specified endpoint.

**Comment by Nomi** [comment]
Implementing POST instead (because that's what the specification says).

**Comment by MateuszWojtynski** [comment]
Should be 'GET' , I guess it is another mistake in API docs
