### ISSUE TITLE
[BACKEND] Create '/api/ingredients' endpoint - 'GET' option.

### ISSUE THREAD

**Issue by MateuszWojtynski** [SoftwareEngineeringGroup3-3/recipe-app-backend#8]
Create '/api/ingredients' endpoint (if not created) with 'GET' option.

Functionality:
`Returns all ingredients to admin panel`

**Comment by MateuszWojtynski** [comment]
This request in API documentation does not have any parameters.

TODO: On what basis are ingredients chosen?

**Comment by Nomi** [comment]
I think ingredients are inputted by the person, and the app gives them the recipes they could use. At least that's how I remember them presenting their app.
